### ISSUE TITLE
Cannot get module to run 

### ISSUE THREAD

**Issue by RafPe** [prgmrcom/ansible-vyos-module#1]
Hey ,

I'm pretty keen to start using your module however I cannot seem to get it working. 

I'm using ansible 2.0.0.2 and have downloaded your files into custom library folder. Content of the library folder looks as follow 

``` bash
-rwxr-xr-x  1 RafPe  staff  4296 Feb  1 12:28 vyos
lrwxr-xr-x  1 RafPe  staff     4 Feb  1 12:28 vyos-check -> vyos
-rw-r--r--  1 RafPe  staff  1495 Feb  1 12:28 vyos-cleanup
```

My yml file looks as follow :

``` yaml

---
- hosts: all
  tasks:
    - vyos: "set system console device ttyS0 speed '115200'"

```

While trying to run it I get the following error 

``` bash
ERROR! this task 'vyos' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
```

Any guides on this one would be appreciated 

Thanks!
